runtime: nodejs20
service: proyekahirfe27-173  # atau sesuaikan nama servicenya
instance_class: F1

handlers:
  - url: /(.*\.(js|css|png|jpg|svg|ico|json|map))
    static_files: build/\1
    upload: build/.*

  - url: /favicon.ico
    static_files: build/favicon.ico
    upload: build/favicon.ico

  - url: /.*
    static_files: build/index.html
    upload: build/index.html

default_expiration: "1h"
