steps:
  # 1. Ambil secret .env dan gcs-key.json ke folder backend
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    dir: backend
    args:
      - -c
      - |
        # Simpan .env di root folder backend
        gcloud secrets versions access latest \
          --secret=backend-env > .env

        # Simpan gcs-key.json ke dalam folder config di backend
        mkdir -p config
        gcloud secrets versions access latest \
          --secret=backend-gcs-key > config/gcs-key.json


  # 1. Build Docker image untuk backend
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/proyekakhirbe27-173", "."]
    dir: "backend"

  # 2. Push ke Container Registry / Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/proyekakhirbe27-173"]

  # 3. Deploy ke Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud
    dir: backend
    args:
      [
        "run",
        "deploy",
        "proyekakhirbe27-173",
        "--image",
        "gcr.io/$PROJECT_ID/proyekakhirbe27-173",
        "--timeout",
        "1000s",
        "--port",
        "3000",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
        "--set-secrets=GCS_KEY=backend-gcs-key:latest",
        "--set-env-vars",
        "ACCESS_TOKEN_SECRET=${_ACCESS_TOKEN_SECRET},REFRESH_TOKEN_SECRET=${_REFRESH_TOKEN_SECRET},DB_HOST=${_DB_HOST},DB_NAME=${_DB_NAME},DB_PASS=${_DB_PASS},DB_USER=${_DB_USER}"
        
      ]

# Log hanya akan disimpan di Google Cloud Logging
# Log tidak akan disimpan di Google Cloud Storage (butuh hak akses).
options:
  logging: CLOUD_LOGGING_ONLY